version: '3'

services:
  pgsql:
    image: postgres:14
    container_name: miht_pgsql
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
    ports:
      - '5444:5432'
    networks:
      - internal
    volumes:
      - ./docker/db/db-data:/var/lib/postgresql/data

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: miht_php-fpm
    networks:
      - internal
    volumes:
      - ./:/var/www/app
    depends_on:
      - pgsql

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: miht_nginx
    ports:
      - "8876:80"
    networks:
      - internal
    volumes:
      - ./:/var/www/app
    depends_on:
      - php-fpm

networks:
  internal:
    driver: bridge