# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
  app.test_command:
    class: AppBundle\Command\TestCommand
    arguments: [ '@doctrine.orm.entity_manager' ]
    tags:
      - { name: 'console.command' }
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
